# Generated by Django 5.0.2 on 2024-03-26 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(max_length=1000)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FRIEND_REQUEST", "Запрос в друзья"),
                            (
                                "FRIEND_REQUEST_ACCEPTED",
                                "Запрос в друзья принят",
                            ),
                            (
                                "FRIEND_REQUEST_REJECTED",
                                "Запрос в друзья отклонен",
                            ),
                        ],
                        max_length=150,
                        null=True,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receive_notifications", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка уведомления",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
    ]
