<<<<<<< HEAD
# Generated by Django 5.0.2 on 2024-03-25 15:34
=======
# Generated by Django 5.0.2 on 2024-02-15 15:02
>>>>>>> 1edccd26d7e53a5992647fad3a6ed69f3e53cced

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
<<<<<<< HEAD
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(max_length=250)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("FRIEND_REQUEST", "Запрос в друзья")],
                        max_length=150,
                        null=True,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
=======
                ("title", models.CharField(max_length=156)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
>>>>>>> 1edccd26d7e53a5992647fad3a6ed69f3e53cced
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
            },
        ),
<<<<<<< HEAD
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receive_notifications", models.BooleanField(default=True)),
                ("friend_requests", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройка уведомления",
                "verbose_name_plural": "Настройки уведомлений",
            },
        ),
=======
>>>>>>> 1edccd26d7e53a5992647fad3a6ed69f3e53cced
    ]
