# Generated by Django 5.0.2 on 2024-02-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="text",
            field=models.TextField(max_length=256),
        ),
    ]
