# Generated by Django 5.0.2 on 2024-03-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationsettings",
            name="friend_requests",
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FRIEND_REQUEST", "Запрос в друзья"),
                    ("FRIEND_REQUEST_ACCEPTED", "Запрос в друзья принят"),
                    ("FRIEND_REQUEST_REJECTED", "Запрос в друзья отклонен"),
                ],
                max_length=150,
                null=True,
            ),
        ),
    ]
