# Generated by Django 5.0.2 on 2024-02-29 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={
                    "invalid": "Введены недопустимые символы",
                    "max_length": "Почта должна содержать от 5 до 254 символов",
                },
                max_length=254,
                unique=True,
                verbose_name="Электронная почта",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                error_messages={
                    "max_length": "Имя должно содержать от 2 до 150 символов",
                    "min_length": "Имя должно содержать от 2 до 150 символов",
                },
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_user_first_name",
                        message="Введены недопустимые символы",
                        regex="^[а-яА-ЯёЁa-zA-Z]+(\\s?\\-?[а-яА-ЯёЁa-zA-Z]+){0,5}$",
                    ),
                    django.core.validators.MinLengthValidator(limit_value=2),
                ],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                error_messages={
                    "max_length": "Имя должно содержать от 2 до 150 символов",
                    "min_length": "Имя должно содержать от 2 до 150 символов",
                },
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_user_last_name",
                        message="Введены недопустимые символы",
                        regex="^[а-яА-ЯёЁa-zA-Z]+(\\s?\\-?[а-яА-ЯёЁa-zA-Z]+){0,5}$",
                    ),
                    django.core.validators.MinLengthValidator(limit_value=2),
                ],
                verbose_name="Фамилия",
            ),
        ),
    ]
