# Generated by Django 5.0.2 on 2024-02-13 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_add_custom_user_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=100, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=40, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=40, verbose_name="Фамилия"),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100,
                        unique=True,
                        verbose_name="Электронная почта",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=40, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=40, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "nickname",
                    models.SlugField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                        verbose_name="Ник пользователя",
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Возраст"
                    ),
                ),
                (
                    "interests",
                    models.JSONField(default=list, verbose_name="Интересы"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Место проживания",
                    ),
                ),
                ("liked_list", models.JSONField(blank=True, default=list)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="",
                        null=True,
                        upload_to="images/profile/",
                        verbose_name="Аватарка",
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Профессия"
                    ),
                ),
                (
                    "character",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Характер"
                    ),
                ),
                (
                    "sex",
                    models.CharField(
                        choices=[("М", "Mужчина"), ("Ж", "Женщина")],
                        default="Ж",
                        help_text="Введите свой пол",
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Цель поиска друга",
                    ),
                ),
                (
                    "network_nick",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        null=True,
                        verbose_name="Ник в других соц.сетях",
                    ),
                ),
                (
                    "additionally",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        verbose_name="Дополнительно",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
    ]
