# Generated by Django 5.0.2 on 2024-02-19 14:10

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_interests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[users.validators.validate_birthday],
                verbose_name="День рождения",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_user_first_name",
                        message="Имя может содержать только буквы и дефис",
                        regex="^[а-яА-ЯёЁa-zA-Z]+\\-?[а-яА-ЯёЁa-zA-Z]+$",
                    )
                ],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_user_last_name",
                        message="Фамилия может содержать только буквы и дефис",
                        regex="^[а-яА-ЯёЁa-zA-Z]+\\-?[а-яА-ЯёЁa-zA-Z]+$",
                    )
                ],
                verbose_name="Фамилия",
            ),
        ),
    ]
