# Generated by Django 5.0.2 on 2024-02-14 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="additionally",
            field=models.TextField(
                blank=True, max_length=150, verbose_name="Дополнительно"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Место проживания",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="network_nick",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Ник в других соц.сетях",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Фамилия"),
        ),
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_added", models.BooleanField(default=False)),
                (
                    "friend",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friend",
                        to="users.profile",
                    ),
                ),
                (
                    "initiator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initiator",
                        to="users.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Друг",
                "verbose_name_plural": "Друзья",
            },
        ),
        migrations.AddConstraint(
            model_name="friend",
            constraint=models.UniqueConstraint(
                fields=("initiator", "friend"), name="unique_friend"
            ),
        ),
    ]
