# Generated by Django 5.0.2 on 2024-02-21 13:23

from pathlib import Path

from django.db import migrations

from config.settings import BASE_DIR

CITIES_FILE = Path(BASE_DIR / "data" / "cities.txt")


def add_cities(apps, schema_editor):
    City = apps.get_model("users", "City")
    with open(CITIES_FILE, encoding="utf-8") as f:
        cities = []
        for line in f:
            city_name = line.strip()
            new_city_obj = City(name=city_name)
            cities.append(new_city_obj)
        City.objects.bulk_create(cities)


def remove_cities(apps, schema_editor):
    City = apps.get_model("users", "City")
    with open(CITIES_FILE, encoding="utf-8") as f:
        for line in f:
            city_name = line.strip()
            City.objects.filter(name=city_name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_add_city_model"),
    ]

    operations = [migrations.RunPython(add_cities, remove_cities)]
