# Generated by Django 5.0.2 on 2024-02-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0004_alter_profile_additionally_alter_profile_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default=1,
                upload_to="images/profile/",
                verbose_name="Аватарка",
            ),
            preserve_default=False,
        ),
    ]
