# Generated by Django 5.0.2 on 2024-02-15 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0004_alter_profile_additionally_alter_profile_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/profile/",
                verbose_name="Аватарка",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="first_name",
            field=models.CharField(
                max_length=150,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_user_first_name",
                        message="First_name must be alphabetic",
                        regex="^[а-яА-ЯёЁa-zA-Z-]+$",
                    )
                ],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="last_name",
            field=models.CharField(
                max_length=150,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_user_last_name",
                        message="Last_name must be alphabetic",
                        regex="^[а-яА-ЯёЁa-zA-Z-]+$",
                    )
                ],
                verbose_name="Фамилия",
            ),
        ),
    ]
