# Generated by Django 5.0.2 on 2024-03-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_blacklist_blacklist_unique_blacklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_geoip_allowed",
            field=models.BooleanField(
                default=False,
                help_text="Разрешено или нет определение геолокации",
                verbose_name="Разрешение поиска геолокации",
            ),
        ),
    ]
