# Generated by Django 5.0.2 on 2024-03-25 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_is_geoip_allowed"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Широта"
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Долгота"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        unique=True,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Геолокация пользователя",
                "verbose_name_plural": "Геолокация пользователя",
            },
        ),
    ]
