# Generated by Django 5.0.2 on 2024-03-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_userlocation_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlocation",
            name="lat",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, verbose_name="Широта"
            ),
        ),
        migrations.AlterField(
            model_name="userlocation",
            name="lon",
            field=models.DecimalField(
                decimal_places=6, max_digits=9, verbose_name="Долгота"
            ),
        ),
    ]
