# Generated by Django 5.0.2 on 2024-02-15 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание мероприятия"),
                ),
                (
                    "event_type",
                    models.CharField(
                        max_length=150, verbose_name="Тип мероприятия"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(verbose_name="Дата мероприятия"),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=150,
                        verbose_name="Место проведения мероприятия",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="images/events/",
                        verbose_name="Фото мероприятия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ("-date",),
            },
        ),
        migrations.CreateModel(
            name="EventMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_organizer", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="EventInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                    ),
                ),
            ],
        ),
    ]
