# Generated by Django 5.0.2 on 2024-02-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название интереса"
                    ),
                ),
            ],
            options={
                "verbose_name": "Интерес",
                "verbose_name_plural": "Интересы",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Название мероприятия"
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Описание мероприятия"),
                ),
                (
                    "event_type",
                    models.CharField(
                        max_length=200, verbose_name="Тип мероприятия"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(verbose_name="Дата мероприятия"),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=200,
                        verbose_name="Место проведения мероприятия",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="events/images/",
                        verbose_name="Фото мероприятия",
                    ),
                ),
                (
                    "interests",
                    models.ManyToManyField(
                        to="events.interest",
                        verbose_name="Интересы мероприятия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ("-date",),
            },
        ),
    ]
