# Generated by Django 5.0.2 on 2024-04-01 20:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Название мероприятия"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание мероприятия")),
                (
                    "event_type",
                    models.CharField(max_length=50, verbose_name="Тип мероприятия"),
                ),
                (
                    "event_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Стоимость мероприятия",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата начала"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Введите тип и название улицы, номер дома",
                        max_length=150,
                        null=True,
                        verbose_name="Улица, дом",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/events/",
                        verbose_name="Фото мероприятия",
                    ),
                ),
                (
                    "min_age",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Минимальный возраст участников",
                    ),
                ),
                (
                    "max_age",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальный возраст участников",
                    ),
                ),
                (
                    "min_count_members",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Минимальное количество участников",
                    ),
                ),
                (
                    "max_count_members",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Максимальное количество участников",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.city",
                        verbose_name="Место проведения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
                "ordering": ("-start_date",),
            },
        ),
        migrations.CreateModel(
            name="EventInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="events.event"
                    ),
                ),
                (
                    "interest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.interest"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Долгота"
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Широта"
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="Мероприятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Геолокация мероприятия",
                "verbose_name_plural": "Геолокация мероприятий",
            },
        ),
        migrations.CreateModel(
            name="EventMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_organizer", models.BooleanField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Участники мероприятия",
                "verbose_name_plural": "Участники мероприятия",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="members",
            field=models.ManyToManyField(
                help_text="Участники мероприятия",
                through="events.EventMember",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Участники",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventmember",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="unique_member"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_date__gte", models.F("start_date")),
                    ("end_date__isnull", True),
                    _connector="OR",
                ),
                name="date_event_constraint",
            ),
        ),
    ]
