# Generated by Django 5.0.2 on 2024-04-04 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "В ожидании"),
                            ("Accepted", "Принято"),
                            ("Declined", "Отклонено"),
                        ],
                        default="Pending",
                        max_length=150,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participation",
                        to="events.event",
                        verbose_name="Мероприятие",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_participation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Инициатор",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_participation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кем обработано",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на мероприятие",
                "verbose_name_plural": "Заявки на мероприятия",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="participationrequest",
            constraint=models.UniqueConstraint(
                fields=("from_user", "event"), name="unique_event_participation"
            ),
        ),
    ]
