# Generated by Django 5.0.2 on 2024-02-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                max_length=150, verbose_name="Тип мероприятия"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="images/events/",
                verbose_name="Фото мероприятия",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(
                max_length=150, verbose_name="Место проведения мероприятия"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                max_length=150, verbose_name="Название мероприятия"
            ),
        ),
        migrations.AlterField(
            model_name="interest",
            name="name",
            field=models.CharField(
                max_length=150, verbose_name="Название интереса"
            ),
        ),
    ]
