# Generated by Django 5.0.2 on 2024-02-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_remove_event_interests_event_members_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="eventmember",
            name="unique_organizer",
        ),
    ]
