# Generated by Django 5.0.2 on 2024-03-27 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_eventmember_event_alter_eventmember_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Введите тип и название улицы, номер дома",
                max_length=150,
                null=True,
                verbose_name="Улица, дом",
            ),
        ),
        migrations.CreateModel(
            name="EventLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Долгота"
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=6, max_digits=9, verbose_name="Широта"
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="events.event",
                        verbose_name="Мероприятие",
                    ),
                ),
            ],
            options={
                "verbose_name": "Геолокация мероприятий",
                "verbose_name_plural": "Геолокация мероприятий",
            },
        ),
    ]
