# Generated by Django 5.0.2 on 2024-02-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_remove_eventmember_unique_organizer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventmember",
            options={
                "verbose_name": "Участники мероприятия",
                "verbose_name_plural": "Участники мероприятия",
            },
        ),
    ]
