# Generated by Django 5.0.2 on 2024-03-20 16:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_eventmember_event_alter_eventmember_user"),
        ("users", "0006_blacklist_blacklist_unique_blacklist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ("-start_date",),
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="max_age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Максимальный возраст участников",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="max_count_members",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Максимальное количество участников",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="min_age",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Минимальный возраст участников",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="min_count_members",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                verbose_name="Минимальное количество участников",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата начала"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.city",
                verbose_name="Место проведения",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_date__gte", models.F("start_date")),
                    ("end_date__isnull", True),
                    _connector="OR",
                ),
                name="date_event_constraint",
            ),
        ),
    ]
