# Generated by Django 5.0.2 on 2024-03-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_event_address_eventlocation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventlocation",
            options={
                "verbose_name": "Геолокация мероприятия",
                "verbose_name_plural": "Геолокация мероприятий",
            },
        ),
    ]
