# Generated by Django 5.0.2 on 2024-03-28 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "events",
            "0006_alter_event_options_remove_event_date_event_end_date_and_more",
        ),
        ("events", "0007_alter_eventlocation_options"),
    ]

    operations = []
