version: '3.8'

services:
  db:
    image: postgres:16.1-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ../../.env

  backend:
    build: ../../.
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ../../.env

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend

volumes:
  db_data:
  static_value:
  media_value:
