version: '3.8'

services:

  backend:
    build: ../../.
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
      - ../../.env
    networks:
      - app_net

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    networks:
      - app_net

networks:
  app_net:
    external: true

volumes:
  db_data:
  static_value:
  media_value:
